"use client";

import { useEffect, useState } from "react";
import "./globals.css";
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const useHasHydrated = () => {
  const [hydrated, setHydrated] = useState<boolean>(false);
  useEffect(() => {
    setHydrated(true);
  }, []);

  return hydrated;
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const hasHydrated = useHasHydrated();

  return (
    <html lang="en">
      <body>{hasHydrated ? children : null}</body>
    </html>
  );
}
